server:
  port: 4000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: <your password>
    url: jdbc:mysql://localhost:3307/<db name>
    username: <your username>

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true


  data:
    redis:
      host: localhost
      port: 6379